# Generated by Django 5.1.4 on 2024-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('NLP', 'Natural Language Processing'), ('CV', 'Computer Vision'), ('TAB', 'Tabular Data'), ('OTHER', 'Other')], max_length=20)),
                ('framework', models.CharField(choices=[('TF', 'TensorFlow'), ('PT', 'PyTorch'), ('ONNX', 'ONNX'), ('OTHER', 'Other')], max_length=20)),
                ('performance_metrics', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='models/')),
                ('owner', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
